### ISSUE TITLE
最新版莫名其妙点进自己歌单就闪退啊！

### ISSUE THREAD

**Issue by limbia** [KusStar/rewind-docs#1]
换了286版本结果一直提示更新，想找288结果也没找着。。可以设置让他不提示更新嘛。。

**Comment by KusStar** [comment]
尝试手动授予存储权限。
不可以不提示。

[Release](https://github.com/KusStar/rewind_docs/releases) 页面可以下载 2.8.9，与 2.8.8 无区别。

> 换了286版本结果一直提示更新，想找288结果也没找着。。可以设置让他不提示更新嘛。。
