### ISSUE TITLE
希望支持打开时恢复上次播放歌单记录(同时定位到上次播放歌曲暂停/退出时自动保存的进度)

### ISSUE THREAD

**Issue by limbia** [KusStar/rewind-docs#2]
希望开发者先别关闭这个帖子，我想集中在这个帖子下面提一些相关意见，免得又开新帖，可以把我这个改成进行中吗？

**Comment by KusStar** [comment]
> 希望开发者先别关闭这个帖子，我想集中在这个帖子下面提一些相关意见，免得又开新帖，可以把我这个改成进行中吗？

反馈不应该在这里的，这是文档仓库。
建议发到邮箱 kussssss@outlook.com

**Comment by limbia** [comment]
> > 希望开发者先别关闭这个帖子，我想集中在这个帖子下面提一些相关意见，免得又开新帖，可以把我这个改成进行中吗？
> 
> 反馈不应该在这里的，这是文档仓库。
> 建议发到邮箱 [kussssss@outlook.com](mailto:kussssss@outlook.com)

好的
