### ISSUE TITLE
在未播放音乐时，最下面的歌单会被三大金刚挡住

### ISSUE THREAD

**Issue by pikakolendo02** [KusStar/rewind-docs#3]
![Screenshot_20210307-115014](https://user-images.githubusercontent.com/15796641/110228455-54a81900-7f3c-11eb-8f5a-a84947c0dca8.png)
![Screenshot_20210307-115953](https://user-images.githubusercontent.com/15796641/110228511-a8b2fd80-7f3c-11eb-9e81-bf989b19a159.png)

即，底部边距只有在播放音乐时才起作用

**Comment by KusStar** [comment]
最下面也是点击得到的，况且这个应用就是来播放音乐的。还有三大金刚也不在适配考虑范围内了。

**Comment by comet200403** [comment]
或许试着可以让播放栏常驻？在不播放的时候就显示程序logo
