### ISSUE TITLE
改进歌曲缓存

### ISSUE THREAD

**Issue by lava081** [KusStar/rewind-docs#7]
1.在我将Rewind更新至3.2.2后，缓存的上限似乎被固定在了1G，自定义一个大于1024的数值将会导致缓存上限被还原成200M，而这似乎不太够用。作为对比网易云音乐安卓端提供近乎无限的缓存上限，而QQ音乐安卓端提供8G的缓存上限。
2.如果能够利用读写外置SD卡的权限将缓存位置转移到安装目录以外的地方就更好了。

**Comment by KusStar** [comment]
1. 缓存似乎命中率不高，调得太高也无济于事，对于播放体验不会有太大影响。
2. 确实有上限在 1GB 的 BUG，考虑下个版本修复。
